on:
  pull_request:
    branches:
      - main

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Main
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_SECRET }}
          protocol: ftp
          server-dir: /
          exclude: |
            **/wp-content/uploads/**
            .htaccess
